function sim = run_single_simulation(cfg, varargin)
%RUN_SINGLE_SIMULATION Run one adaptive REQ synthetic simulation.
%
% Usage:
%   sim = adaptive_req.simulate.run_single_simulation(cfg);
%   sim = adaptive_req.simulate.run_single_simulation(cfg, 'Seed', 10);

cfg = update_struct_from_name_value(cfg, varargin{:});

sim_args = struct_to_valid_simulation_args(cfg);

[Uxz, x, z, cs_map, k_map, diag] = ...
    adaptive_req.simulate.simulate_rswe_plane(sim_args{:});

sim = struct();

sim.Uxz = Uxz;
sim.x = x;
sim.z = z;
sim.cs_map = cs_map;
sim.k_map = k_map;
sim.diag = diag;
sim.cfg = cfg;

sim.output_convention = 'Uxz(z,x), cs_map(z,x), k_map(z,x)';

end

function args = struct_to_valid_simulation_args(cfg)

valid_names = { ...
    'MaskConfig', ...
    'MaskType', ...
    'cs_bg', ...
    'cs_inc', ...
    'MaskParams', ...
    'Lx', ...
    'Lz', ...
    'dx', ...
    'dz', ...
    'f0', ...
    'y0', ...
    'Nwaves', ...
    'rmin', ...
    'rmax', ...
    'AmpJitter', ...
    'DecayAlpha', ...
    'Seed', ...
    'UseParfor', ...
    'PhiRange', ...
    'ThetaRange', ...
    'SNR', ...
    'Is2D', ...
    'AngleRange2D', ...
    'SourceSampling', ...
    'AngularSamplingMethod', ...
    'ForceInPlaneWave', ...
    'ConeAxis', ...
    'ConeHalfAngleDeg', ...
    'BandAxis', ...
    'BandHalfWidthDeg', ...
    'WaveModel'};

args = {};

for i = 1:numel(valid_names)
    name = valid_names{i};

    if isfield(cfg, name)
        args(end+1:end+2) = {name, cfg.(name)}; %#ok<AGROW>
    end
end

end

function s = update_struct_from_name_value(s, varargin)

if isempty(varargin)
    return;
end

if mod(numel(varargin), 2) ~= 0
    error('Optional inputs must be name-value pairs.');
end

for i = 1:2:numel(varargin)
    name = varargin{i};
    value = varargin{i+1};

    if ~(ischar(name) || isstring(name))
        error('Parameter name must be char or string.');
    end

    s.(char(name)) = value;
end

end
