function outcome = evaluate_kwsim_frozen_models( ...
    sample_file, bundle_file, options)
%EVALUATE_KWSIM_FROZEN_MODELS Apply frozen REQ models to one KWSIM sample.
%
% This is an external-validation smoke integration. It does not train,
% recalibrate, tune, or otherwise modify the frozen models.

arguments
    sample_file {mustBeTextScalar}
    bundle_file {mustBeTextScalar}

    options.M (1,1) double = 2
    options.CsGuessMPerS (1,1) double = 3.0
    options.TargetStepM (1,1) double = 1e-3
    options.OutputDirectory (1,1) string = ""
    options.UseWindowParfor (1,1) logical = false
end

data = ...
    adaptive_req.integration. ...
    load_kwsim_validation_sample(sample_file);

[bundle, bundle_metadata] = ...
    adaptive_req.inference.load_model_bundle( ...
        bundle_file);

truth_values = ...
    data.truth.cs_m_s_zx(:);

truth_reference_m_s = ...
    median(truth_values, "omitnan");

truth_relative_range = ...
    (max(truth_values) - min(truth_values)) / ...
    max(abs(truth_reference_m_s), eps);

if truth_relative_range > 1e-6
    error( ...
        "adaptive_req:FrozenSmokeRequiresHomogeneousTruth", ...
        "Initial frozen-model smoke supports homogeneous truth only.");
end

physical_cfg = struct();

physical_cfg.f0 = ...
    data.frequency_hz;

physical_cfg.dx = ...
    data.dx_m;

physical_cfg.dz = ...
    data.dz_m;

physical_cfg.cs_bg = ...
    truth_reference_m_s;

physical_cfg.WaveModel = ...
    "kWave_projected_3D";

feature_cfg = ...
    adaptive_req.config.default_feature_config( ...
        "M", options.M, ...
        "cs_guess", options.CsGuessMPerS, ...
        "gamma_win", 1.0, ...
        "pad_factor", 1);

step_x = max( ...
    1, ...
    round(options.TargetStepM / data.dx_m));

step_z = max( ...
    1, ...
    round(options.TargetStepM / data.dz_m));

fprintf("\n============================================\n");
fprintf("KWSIM -> frozen REQ models\n");
fprintf("============================================\n");

fprintf("Sample:       %s\n", data.sample_file);
fprintf("Bundle:       %s\n", bundle_metadata.path);
fprintf("Field size:   %d x %d [Nz,Nx]\n", ...
    size(data.wavefield_zx, 1), ...
    size(data.wavefield_zx, 2));
fprintf("f0:           %.3f Hz\n", data.frequency_hz);
fprintf("M:            %.3f\n", options.M);
fprintf("cs_guess:     %.3f m/s\n", options.CsGuessMPerS);
fprintf("Step x/z:     %d / %d pixels\n", step_x, step_z);

%% Extract the same feature family used by the frozen models

req_output = ...
    adaptive_req.estimators.req_estimator_map( ...
        data.wavefield_zx, ...
        physical_cfg, ...
        feature_cfg, ...
        "StepX", step_x, ...
        "StepZ", step_z, ...
        "EdgeMode", "valid", ...
        "QuantileMode", "theory_discrete", ...
        "TheoryFieldType", "SingleWave", ...
        "TheoryMode", "S2D", ...
        "ReqOptions", { ...
            "Nbins", "auto", ...
            "Nbins_auto_oversample", 1, ...
            "Nbins_min", 16, ...
            "smooth_sigma", 1}, ...
        "ReturnFeatures", false, ...
        "ReturnFeatureTable", true, ...
        "ReuseReqSpectrumForFeatures", true, ...
        "StoreReqCurves", false, ...
        "UseWindowParfor", options.UseWindowParfor, ...
        "Verbose", false);

features = ...
    req_output.feature_table;

number_of_rows = ...
    height(features);

if number_of_rows == 0
    error( ...
        "adaptive_req:NoKwsimFeatureRows", ...
        "REQ produced no feature rows.");
end

% Operational metadata used during model training.
features.REQ_M = ...
    options.M * ones(number_of_rows, 1);

features.M = ...
    options.M * ones(number_of_rows, 1);

features.SIM_f0 = ...
    data.frequency_hz * ones(number_of_rows, 1);

features.REQ_StepX = ...
    step_x * ones(number_of_rows, 1);

features.REQ_StepZ = ...
    step_z * ones(number_of_rows, 1);

features.TargetStepM = ...
    options.TargetStepM * ones(number_of_rows, 1);

features.f0 = ...
    data.frequency_hz * ones(number_of_rows, 1);

features.dx = ...
    data.dx_m * ones(number_of_rows, 1);

features.dz = ...
    data.dz_m * ones(number_of_rows, 1);

%% Apply the frozen model family

[model_predictions, augmented_features, composition] = ...
    adaptive_req.inference.predict_frozen_models( ...
        features, ...
        bundle);

%% Add the discrete SingleWave reference

theory_predictions = table();

theory_predictions.source_row = ...
    (1:number_of_rows).';

theory_predictions.model_name = ...
    repmat( ...
        "theory_discrete_single_wave", ...
        number_of_rows, 1);

theory_predictions.q_raw = ...
    req_output.theory.q_th * ...
    ones(number_of_rows, 1);

theory_predictions.q_pred = ...
    theory_predictions.q_raw;

theory_predictions.predicted_patch_purity = ...
    composition.predicted_patch_purity;

theory_predictions.p_mixed = ...
    composition.p_mixed;

theory_predictions.p_strong_mixed = ...
    composition.p_strong_mixed;

coordinate_names = [
    "map_iz"
    "map_ix"
    "cx"
    "cz"
    "x_center_m"
    "z_center_m"
];

for coordinate_name = coordinate_names.'
    if ismember( ...
            coordinate_name, ...
            string(features.Properties.VariableNames))
        theory_predictions.(coordinate_name) = ...
            features.(coordinate_name);
    end
end

predictions = ...
    vertcat( ...
        theory_predictions, ...
        model_predictions);

%% Convert each predicted q to SWS

predictions.SWS_pred_m_s = ...
    nan(height(predictions), 1);

model_names = ...
    unique(predictions.model_name, "stable");

for model_name = model_names.'
    mask = ...
        predictions.model_name == model_name;

    source_rows = ...
        predictions.source_row(mask);

    mappings = ...
        features.req_mapping(source_rows);

    predictions.SWS_pred_m_s(mask) = ...
        adaptive_req.inference.quantiles_to_sws( ...
            mappings, ...
            predictions.q_pred(mask), ...
            data.frequency_hz);
end

%% Align truth to each window center

center_indices = ...
    sub2ind( ...
        size(data.truth.cs_m_s_zx), ...
        features.cz, ...
        features.cx);

truth_by_source_row = ...
    data.truth.cs_m_s_zx(center_indices);

predictions.SWS_true_m_s = ...
    truth_by_source_row( ...
        predictions.source_row);

predictions.valid = ...
    isfinite(predictions.q_pred) & ...
    isfinite(predictions.SWS_pred_m_s) & ...
    isfinite(predictions.SWS_true_m_s) & ...
    predictions.SWS_true_m_s > 0;

predictions.signed_error_pct = ...
    100 * ...
    (predictions.SWS_pred_m_s - ...
     predictions.SWS_true_m_s) ./ ...
    predictions.SWS_true_m_s;

predictions.abs_error_pct = ...
    abs(predictions.signed_error_pct);

%% Summarize each model

metrics = summarize_predictions(predictions);

disp(metrics);

outcome = struct();

outcome.sample = data;
outcome.bundle_metadata = bundle_metadata;
outcome.req_output = req_output;
outcome.features = features;
outcome.augmented_features = augmented_features;
outcome.predictions = predictions;
outcome.metrics = metrics;

if strlength(options.OutputDirectory) > 0
    output_directory = ...
        string(options.OutputDirectory);

    if ~isfolder(output_directory)
        mkdir(output_directory);
    end

    result_path = fullfile( ...
        output_directory, ...
        "kwsim_frozen_models_result.mat");

    prediction_path = fullfile( ...
        output_directory, ...
        "kwsim_frozen_models_patch_results.csv");

    metrics_path = fullfile( ...
        output_directory, ...
        "kwsim_frozen_models_summary.csv");

    save(result_path, "outcome", "-v7.3");
    writetable(predictions, prediction_path);
    writetable(metrics, metrics_path);

    outcome.output_paths = struct();
    outcome.output_paths.result = string(result_path);
    outcome.output_paths.predictions = string(prediction_path);
    outcome.output_paths.metrics = string(metrics_path);

    fprintf("\nSaved frozen-model smoke to:\n%s\n", ...
        output_directory);
else
    outcome.output_paths = struct();
end

end


function metrics = summarize_predictions(predictions)

model_names = ...
    unique(predictions.model_name, "stable");

parts = cell(numel(model_names), 1);

for index = 1:numel(model_names)
    model_name = model_names(index);

    rows = ...
        predictions( ...
            predictions.model_name == model_name, :);

    valid_rows = ...
        rows(rows.valid, :);

    result = table();

    result.model_name = model_name;
    result.N = height(rows);
    result.valid_fraction = ...
        height(valid_rows) / max(height(rows), 1);

    result.mean_q = ...
        mean(valid_rows.q_pred, "omitnan");

    result.mean_SWS_m_s = ...
        mean(valid_rows.SWS_pred_m_s, "omitnan");

    result.median_SWS_m_s = ...
        median(valid_rows.SWS_pred_m_s, "omitnan");

    result.MAPE_pct = ...
        mean(valid_rows.abs_error_pct, "omitnan");

    result.median_APE_pct = ...
        median(valid_rows.abs_error_pct, "omitnan");

    result.bias_pct = ...
        mean(valid_rows.signed_error_pct, "omitnan");

    result.CoV_pct = ...
        100 * ...
        std(valid_rows.SWS_pred_m_s, 0, "omitnan") / ...
        max(abs(mean( ...
            valid_rows.SWS_pred_m_s, ...
            "omitnan")), eps);

    result.maximum_APE_pct = ...
        max(valid_rows.abs_error_pct);

    parts{index} = result;
end

metrics = ...
    vertcat(parts{:});

end
