function outcome = evaluate_kwsim_req_smoke( ...
    sample_file, options)
%EVALUATE_KWSIM_REQ_SMOKE Run a non-ML REQ integration smoke test.
%
% This function tests the interface:
%
%   KWSIM sample
%       -> adaptive_req loader
%       -> project-native REQ estimator
%       -> SWS map
%       -> comparison with KWSIM truth
%
% The operational quantile is obtained from the discretized SingleWave
% theory. The oracle local_req quantile is not used for prediction.
%
% This first smoke test supports homogeneous samples only.

arguments
    sample_file {mustBeTextScalar}

    options.M (1,1) double = 2

    options.CsGuessMPerS (1,1) double = 3.0

    options.TargetStepM (1,1) double = 1e-3

    options.OutputDirectory (1,1) string = ""

    options.UseWindowParfor (1,1) logical = false
end

validate_options(options);

data = ...
    adaptive_req.integration. ...
    load_kwsim_validation_sample( ...
        sample_file);

%% Confirm this first smoke case is homogeneous

truth_values = ...
    data.truth.cs_m_s_zx(:);

cs_reference_m_s = ...
    median(truth_values, "omitnan");

truth_relative_range = ...
    (max(truth_values) - min(truth_values)) / ...
    max(abs(cs_reference_m_s), eps);

if truth_relative_range > 1e-6
    error( ...
        "adaptive_req:KwsimSmokeRequiresHomogeneousTruth", ...
        ["The initial KWSIM smoke integration supports only " ...
         "homogeneous truth maps. Relative SWS range: %.6g."], ...
        truth_relative_range);
end

%% Build the existing REQ configuration

req_physical_cfg = struct();

req_physical_cfg.f0 = ...
    data.frequency_hz;

req_physical_cfg.dx = ...
    data.dx_m;

req_physical_cfg.dz = ...
    data.dz_m;

% Used here only to construct the directional discrete-theory benchmark
% and to report descriptive error against the homogeneous known truth.
req_physical_cfg.cs_bg = ...
    cs_reference_m_s;

req_physical_cfg.WaveModel = ...
    "kWave_projected_3D";

feature_cfg = ...
    adaptive_req.config.default_feature_config( ...
        "M", options.M, ...
        "cs_guess", options.CsGuessMPerS, ...
        "gamma_win", 1.0, ...
        "pad_factor", 1);

step_x = max( ...
    1, ...
    round(options.TargetStepM / data.dx_m));

step_z = max( ...
    1, ...
    round(options.TargetStepM / data.dz_m));

fprintf("\n============================================\n");
fprintf("KWSIM -> REQ smoke integration\n");
fprintf("============================================\n");

fprintf("Sample:             %s\n", ...
    data.sample_file);

fprintf("Physical source:    %dD\n", ...
    data.source_dimension);

fprintf("Exported field:     %d x %d [Nz,Nx]\n", ...
    size(data.wavefield_zx, 1), ...
    size(data.wavefield_zx, 2));

fprintf("Quantity:           %s (%s)\n", ...
    data.quantity, ...
    data.units);

fprintf("Frequency:          %.3f Hz\n", ...
    data.frequency_hz);

fprintf("Sampling dx/dz:     %.3f / %.3f mm\n", ...
    1e3 * data.dx_m, ...
    1e3 * data.dz_m);

fprintf("REQ M:              %.3f\n", ...
    options.M);

fprintf("REQ cs_guess:       %.3f m/s\n", ...
    options.CsGuessMPerS);

fprintf("REQ step x/z:       %d / %d pixels\n", ...
    step_x, ...
    step_z);

%% Run the reusable REQ estimator

req_output = ...
    adaptive_req.estimators.req_estimator_map( ...
        data.wavefield_zx, ...
        req_physical_cfg, ...
        feature_cfg, ...
        "StepX", step_x, ...
        "StepZ", step_z, ...
        "EdgeMode", "valid", ...
        "QuantileMode", "theory_discrete", ...
        "TheoryFieldType", "SingleWave", ...
        "TheoryMode", "S2D", ...
        "ReqOptions", { ...
            "Nbins", "auto", ...
            "Nbins_auto_oversample", 1, ...
            "Nbins_min", 16, ...
            "smooth_sigma", 1}, ...
        "ReturnFeatures", false, ...
        "ReturnFeatureTable", true, ...
        "ReuseReqSpectrumForFeatures", true, ...
        "StoreReqCurves", false, ...
        "UseWindowParfor", options.UseWindowParfor, ...
        "Verbose", false);

%% Align KWSIM truth with the REQ map centers

truth_at_centers = ...
    data.truth.cs_m_s_zx( ...
        req_output.z_idx, ...
        req_output.x_idx);

if ~isequal( ...
        size(truth_at_centers), ...
        size(req_output.cs_map))
    error( ...
        "adaptive_req:KwsimReqAlignmentFailed", ...
        "REQ map and sampled truth map have inconsistent sizes.");
end

valid_mask = ...
    req_output.valid_map & ...
    isfinite(req_output.cs_map) & ...
    isfinite(truth_at_centers) & ...
    truth_at_centers > 0;

if ~any(valid_mask, "all")
    error( ...
        "adaptive_req:KwsimReqNoValidPredictions", ...
        "REQ produced no valid SWS predictions.");
end

predicted_sws = ...
    req_output.cs_map(valid_mask);

true_sws = ...
    truth_at_centers(valid_mask);

signed_error_pct = ...
    100 * ...
    (predicted_sws - true_sws) ./ ...
    true_sws;

absolute_error_pct = ...
    abs(signed_error_pct);

metrics = struct();

metrics.valid_count = ...
    nnz(valid_mask);

metrics.total_count = ...
    numel(valid_mask);

metrics.valid_fraction = ...
    metrics.valid_count / ...
    metrics.total_count;

metrics.mean_predicted_sws_m_s = ...
    mean(predicted_sws, "omitnan");

metrics.median_predicted_sws_m_s = ...
    median(predicted_sws, "omitnan");

metrics.true_sws_m_s = ...
    cs_reference_m_s;

metrics.MAPE_pct = ...
    mean(absolute_error_pct, "omitnan");

metrics.median_APE_pct = ...
    median(absolute_error_pct, "omitnan");

metrics.bias_pct = ...
    mean(signed_error_pct, "omitnan");

metrics.RMSE_pct = ...
    sqrt(mean( ...
        signed_error_pct.^2, ...
        "omitnan"));

metrics.CoV_pct = ...
    100 * ...
    std(predicted_sws, 0, "omitnan") / ...
    max(abs(mean( ...
        predicted_sws, ...
        "omitnan")), eps);

metrics.maximum_APE_pct = ...
    max(absolute_error_pct);

metrics.q_theory_discrete = ...
    double(req_output.theory.q_th);

metrics.window_size_points = ...
    req_output.win_size;

metrics.map_size_zx = ...
    size(req_output.cs_map);

feature_row_count = ...
    height(req_output.feature_table);

interface_checks = struct();

interface_checks.wavefield_orientation_valid = ...
    isequal( ...
        size(data.wavefield_zx), ...
        [numel(data.axes.z_m), ...
         numel(data.axes.x_m)]);

interface_checks.req_map_truth_alignment_valid = ...
    isequal( ...
        size(req_output.cs_map), ...
        size(truth_at_centers));

interface_checks.feature_row_count_valid = ...
    feature_row_count == ...
    numel(req_output.cs_map);

interface_checks.has_valid_predictions = ...
    metrics.valid_count > 0;

interface_checks.predictions_finite = ...
    all(isfinite(predicted_sws));

interface_valid = all( ...
    struct2array(interface_checks));

report = struct();

report.interface_valid = ...
    interface_valid;

report.interface_checks = ...
    interface_checks;

report.metrics = ...
    metrics;

report.truth_relative_range = ...
    truth_relative_range;

report.summary = sprintf([ ...
    'interface valid=%d, q_theory=%.5f, ', ...
    'map=%dx%d, valid=%.1f%%, ', ...
    'SWS mean=%.5f m/s, MAPE=%.3f%%, ', ...
    'bias=%.3f%%, CoV=%.3f%%'], ...
    interface_valid, ...
    metrics.q_theory_discrete, ...
    metrics.map_size_zx(1), ...
    metrics.map_size_zx(2), ...
    100 * metrics.valid_fraction, ...
    metrics.mean_predicted_sws_m_s, ...
    metrics.MAPE_pct, ...
    metrics.bias_pct, ...
    metrics.CoV_pct);

%% Build one patch-level result table

[X_center_m, Z_center_m] = meshgrid( ...
    req_output.x_m, ...
    req_output.z_m);

patch_results = table();

patch_results.map_iz = ...
    repelem((1:size(req_output.cs_map, 1)).', ...
        size(req_output.cs_map, 2));

patch_results.map_ix = ...
    repmat((1:size(req_output.cs_map, 2)).', ...
        size(req_output.cs_map, 1), 1);

patch_results.x_center_m = ...
    X_center_m(:);

patch_results.z_center_m = ...
    Z_center_m(:);

patch_results.q_pred = ...
    req_output.q_map(:);

patch_results.SWS_true_m_s = ...
    truth_at_centers(:);

patch_results.SWS_pred_m_s = ...
    req_output.cs_map(:);

patch_results.valid = ...
    valid_mask(:);

patch_results.signed_error_pct = ...
    100 * ...
    (patch_results.SWS_pred_m_s - ...
     patch_results.SWS_true_m_s) ./ ...
    patch_results.SWS_true_m_s;

patch_results.abs_error_pct = ...
    abs(patch_results.signed_error_pct);

%% Package outcome

outcome = struct();

outcome.sample = data;
outcome.req_output = req_output;
outcome.truth_at_centers_zx = truth_at_centers;
outcome.valid_mask_zx = valid_mask;
outcome.patch_results = patch_results;
outcome.report = report;

fprintf("\nSmoke result:\n%s\n", ...
    report.summary);

%% Save smoke outputs

if strlength(options.OutputDirectory) > 0
    output_directory = ...
        string(options.OutputDirectory);

    if ~isfolder(output_directory)
        mkdir(output_directory);
    end

    result_path = fullfile( ...
        output_directory, ...
        "kwsim_req_smoke_result.mat");

    table_path = fullfile( ...
        output_directory, ...
        "kwsim_req_smoke_patch_results.csv");

    summary_path = fullfile( ...
        output_directory, ...
        "kwsim_req_smoke_summary.txt");

    save( ...
        result_path, ...
        "outcome", ...
        "-v7.3");

    writetable( ...
        patch_results, ...
        table_path);

    write_summary( ...
        report, ...
        data, ...
        req_output, ...
        summary_path);

    outcome.output_paths = struct();

    outcome.output_paths.result = ...
        string(result_path);

    outcome.output_paths.patch_table = ...
        string(table_path);

    outcome.output_paths.summary = ...
        string(summary_path);

    fprintf("\nSaved smoke integration to:\n%s\n", ...
        output_directory);
else
    outcome.output_paths = struct();
end

if ~report.interface_valid
    error( ...
        "adaptive_req:KwsimReqSmokeFailed", ...
        "KWSIM -> REQ interface checks failed.");
end

end


function validate_options(options)

if options.M <= 0
    error( ...
        "adaptive_req:InvalidSmokeConfiguration", ...
        "M must be positive.");
end

if options.CsGuessMPerS <= 0
    error( ...
        "adaptive_req:InvalidSmokeConfiguration", ...
        "CsGuessMPerS must be positive.");
end

if options.TargetStepM <= 0
    error( ...
        "adaptive_req:InvalidSmokeConfiguration", ...
        "TargetStepM must be positive.");
end

end


function write_summary( ...
    report, data, req_output, summary_path)

file_id = fopen( ...
    summary_path, ...
    "w");

if file_id < 0
    error( ...
        "adaptive_req:SmokeOutputWriteFailed", ...
        "Could not write smoke summary: %s", ...
        summary_path);
end

cleanup = onCleanup( ...
    @() fclose(file_id));

fprintf(file_id, ...
    "KWSIM -> REQ SMOKE INTEGRATION\n");

fprintf(file_id, ...
    "==============================\n\n");

fprintf(file_id, ...
    "Sample file: %s\n", ...
    data.sample_file);

fprintf(file_id, ...
    "Source dimension: %dD\n", ...
    data.source_dimension);

fprintf(file_id, ...
    "Exported field size [Nz,Nx]: %s\n", ...
    mat2str(size(data.wavefield_zx)));

fprintf(file_id, ...
    "REQ map size [Nz,Nx]: %s\n", ...
    mat2str(size(req_output.cs_map)));

fprintf(file_id, ...
    "Frequency: %.6g Hz\n", ...
    data.frequency_hz);

fprintf(file_id, ...
    "dx: %.9g m\n", ...
    data.dx_m);

fprintf(file_id, ...
    "dz: %.9g m\n", ...
    data.dz_m);

fprintf(file_id, ...
    "Quantity: %s\n", ...
    data.quantity);

fprintf(file_id, ...
    "Units: %s\n", ...
    data.units);

fprintf(file_id, ...
    "Phasor convention: %s\n\n", ...
    data.phasor_convention);

fprintf(file_id, ...
    "%s\n\n", ...
    report.summary);

check_names = ...
    fieldnames(report.interface_checks);

fprintf(file_id, ...
    "Interface checks\n");

fprintf(file_id, ...
    "----------------\n");

for index = 1:numel(check_names)
    name = check_names{index};

    fprintf(file_id, ...
        "%-40s %d\n", ...
        name, ...
        report.interface_checks.(name));
end

fprintf(file_id, ...
    "\nDescriptive accuracy metrics\n");

fprintf(file_id, ...
    "----------------------------\n");

metric_names = ...
    fieldnames(report.metrics);

for index = 1:numel(metric_names)
    name = metric_names{index};
    value = report.metrics.(name);

    if isnumeric(value) && isscalar(value)
        fprintf(file_id, ...
            "%-40s %.10g\n", ...
            name, ...
            value);
    elseif isnumeric(value)
        fprintf(file_id, ...
            "%-40s %s\n", ...
            name, ...
            mat2str(value));
    end
end

clear cleanup

end
