function COL = detect_mc_columns(T)
%DETECT_MC_COLUMNS Detect important columns in an MC output table.
%
% Usage
%   COL = adaptive_req.analysis.detect_mc_columns(T_mc);
%
% Output
%   COL:
%       Structure with detected column names.

vars = string(T.Properties.VariableNames);

COL = struct();

COL.q = find_first_existing_var(vars, { ...
    'q_theory', ...
    'q', ...
    'q_val', ...
    'q_reference'});

COL.omega = find_first_existing_var(vars, { ...
    'Omega_sr', ...
    'Omega', ...
    'omega_sr', ...
    'solid_angle', ...
    'solid_angle_sr'});

COL.condition = find_first_existing_var(vars, { ...
    'condition_id'});

COL.condition_position = find_first_existing_var(vars, { ...
    'condition_position'});

COL.condition_label = find_first_existing_var(vars, { ...
    'condition_label'});

COL.step = find_first_existing_var(vars, { ...
    'step_idx', ...
    'step_id', ...
    'aperture_step', ...
    'step'});

COL.realization = find_first_existing_var(vars, { ...
    'realization_idx', ...
    'realization_id', ...
    'rep_idx', ...
    'rep', ...
    'irep'});

COL.patch = find_first_existing_var(vars, { ...
    'patch_idx', ...
    'patch_id', ...
    'patch'});

COL.wave_model = find_first_existing_var(vars, { ...
    'SIM_WaveModel', ...
    'WaveModel', ...
    'wave_model'});

COL.f0 = find_first_existing_var(vars, { ...
    'SIM_f0', ...
    'f0'});

COL.cs_bg = find_first_existing_var(vars, { ...
    'SIM_cs_bg', ...
    'cs_bg'});

COL.M = find_first_existing_var(vars, { ...
    'REQ_M', ...
    'M'});

COL.params = vars(startsWith(vars, "SIM_") | startsWith(vars, "REQ_"));

exclude = [ ...
    COL.q, ...
    COL.omega, ...
    COL.condition, ...
    COL.condition_position, ...
    COL.step, ...
    COL.realization, ...
    COL.patch];

exclude = exclude(exclude ~= "");

COL.params = COL.params(~ismember(COL.params, exclude));

COL.available_vars = vars;

end

function var_name = find_first_existing_var(vars, candidates)

vars = string(vars);
candidates = string(candidates);

var_name = "";

for i = 1:numel(candidates)

    idx = find(strcmpi(vars, candidates(i)), 1);

    if ~isempty(idx)
        var_name = vars(idx);
        return;
    end
end

end
