function feature_vars = detect_feature_variables(T, varargin)
%DETECT_FEATURE_VARIABLES Detect true local feature columns in a table.
%
% This function tries to exclude metadata, simulation parameters, aperture
% parameters, and REQ configuration parameters.
%
% The goal is to return local spectral features only.

p = inputParser;
p.FunctionName = 'adaptive_req.analysis.detect_feature_variables';

addRequired(p, 'T', @istable);

addParameter(p, 'ExcludeVars', string.empty(1, 0), ...
    @(x) isstring(x) || iscellstr(x) || ischar(x));

addParameter(p, 'IncludeVars', string.empty(1, 0), ...
    @(x) isstring(x) || iscellstr(x) || ischar(x));

addParameter(p, 'Verbose', true, ...
    @(x) islogical(x) || isnumeric(x));

parse(p, T, varargin{:});

exclude_vars = string(p.Results.ExcludeVars);
include_vars = string(p.Results.IncludeVars);
verbose = logical(p.Results.Verbose);

vars = string(T.Properties.VariableNames);
vars_lower = lower(vars);

is_numeric = false(size(vars));

for i = 1:numel(vars)
    is_numeric(i) = isnumeric(T.(char(vars(i))));
end

%% ------------------------------------------------------------------------
% Explicit variables that are not local features
% -------------------------------------------------------------------------

not_feature_exact = lower(string({ ...
    'condition_id', ...
    'condition_position', ...
    'condition_label', ...
    'step_idx', ...
    'step_id', ...
    'realization_idx', ...
    'realization_id', ...
    'rep_idx', ...
    'patch_idx', ...
    'patch_id', ...
    'seed', ...
    'Seed', ...
    'q', ...
    'q_theory', ...
    'q_val', ...
    'q_reference', ...
    'Omega', ...
    'Omega_sr', ...
    'omega_mean', ...
    'omega_std', ...
    'solid_angle', ...
    'solid_angle_sr', ...
    'aperture_value', ...
    'ConeHalfAngleDeg', ...
    'BandHalfWidthDeg', ...
    'ConeAxis', ...
    'BandAxis', ...
    'f0', ...
    'cs_bg', ...
    'cs_inc', ...
    'Nwaves', ...
    'SNR', ...
    'AmpJitter', ...
    'Lx', ...
    'Lz', ...
    'dx', ...
    'dz', ...
    'M', ...
    'REQ_M', ...
    'gamma_win', ...
    'pad_factor', ...
    'smooth_sigma', ...
    'Nbins', ...
    'Nbins_effective', ...
    'win_size', ...
    'half_win', ...
    'lambda_true', ...
    'lambda_guess', ...
    'lambda_guess_used', ...
    'cs_guess', ...
    'cs_guess_used', ...
    'k0_true', ...
    'M_eff'}));

is_not_feature_exact = ismember(vars_lower, not_feature_exact);

%% ------------------------------------------------------------------------
% Prefixes that are not local features
% -------------------------------------------------------------------------

not_feature_prefixes = lower(string({ ...
    'sim_', ...
    'req_', ...
    'cfg_', ...
    'run_', ...
    'save_', ...
    'plot_', ...
    'output_', ...
    'condition', ...
    'realization', ...
    'patch', ...
    'step', ...
    'seed', ...
    'omega', ...
    'aperture', ...
    'cone', ...
    'band', ...
    'q_', ...
    'cs_', ...
    'lambda', ...
    'win_', ...
    'half_', ...
    'nbins'}));

is_not_feature_prefix = false(size(vars));

for k = 1:numel(not_feature_prefixes)
    is_not_feature_prefix = is_not_feature_prefix | ...
        startsWith(vars_lower, not_feature_prefixes(k));
end

%% ------------------------------------------------------------------------
% Feature keywords
% -------------------------------------------------------------------------

feature_keywords = lower(string({ ...
    'entropy', ...
    'ang_', ...
    'anisotropy', ...
    'coherence', ...
    'concentration', ...
    'sharpness', ...
    'peak_ratio', ...
    'peakiness', ...
    'centroid', ...
    'spread', ...
    'bandwidth', ...
    'width_norm', ...
    'radial_', ...
    'angular_', ...
    'spectral_', ...
    'moment', ...
    'kurtosis', ...
    'skewness', ...
    'isotropy', ...
    'directionality'}));

is_feature_keyword = false(size(vars));

for k = 1:numel(feature_keywords)
    is_feature_keyword = is_feature_keyword | ...
        contains(vars_lower, feature_keywords(k));
end

%% ------------------------------------------------------------------------
% Final mask
% -------------------------------------------------------------------------

is_excluded = ismember(vars, exclude_vars);

mask = ...
    is_numeric & ...
    is_feature_keyword & ...
    ~is_not_feature_exact & ...
    ~is_not_feature_prefix & ...
    ~is_excluded;

feature_vars = vars(mask);

%% ------------------------------------------------------------------------
% Manual include override
% -------------------------------------------------------------------------

if ~isempty(include_vars)

    include_vars = include_vars(ismember(include_vars, vars));

    feature_vars = unique([feature_vars(:); include_vars(:)], 'stable');

end

if verbose
    fprintf('\nDetected local feature variables:\n');

    if isempty(feature_vars)
        fprintf('  None detected.\n');
    else
        disp(feature_vars(:));
    end
end

end
