function [T_feature, T_group] = summarize_feature_q_evidence(T_assoc, varargin)
%SUMMARIZE_FEATURE_Q_EVIDENCE Summarize whether features are associated with q.
%
% Purpose
%   Converts a long association table into a compact evidence summary.
%
%   This function does not assume a purely linear relation. The main
%   decision is based on Spearman rho, which detects monotonic associations.
%
% Usage
%   [T_feature, T_group] = adaptive_req.analysis.summarize_feature_q_evidence( ...
%       T_assoc_controlled, ...
%       'Label', 'controlled');
%
% Inputs
%   T_assoc:
%       Table generated by compute_groupwise_feature_q_associations.
%
% Outputs
%   T_feature:
%       One row per feature with an automatic evidence decision.
%
%   T_group:
%       Original group-level table plus row-level evidence labels.

p = inputParser;
p.FunctionName = 'adaptive_req.analysis.summarize_feature_q_evidence';

addRequired(p, 'T_assoc', @istable);

addParameter(p, 'Label', 'association_summary', ...
    @(x) ischar(x) || isstring(x));

addParameter(p, 'FeatureNameVar', 'feature_name', ...
    @(x) ischar(x) || isstring(x));

addParameter(p, 'RhoVar', 'spearman_rho', ...
    @(x) ischar(x) || isstring(x));

addParameter(p, 'PearsonVar', 'pearson_r', ...
    @(x) ischar(x) || isstring(x));

addParameter(p, 'KendallVar', 'kendall_tau', ...
    @(x) ischar(x) || isstring(x));

addParameter(p, 'LinearR2Var', 'linear_R2', ...
    @(x) ischar(x) || isstring(x));

addParameter(p, 'PVar', 'spearman_p', ...
    @(x) ischar(x) || isstring(x));

addParameter(p, 'NVar', 'n_valid', ...
    @(x) ischar(x) || isstring(x));

addParameter(p, 'MinN', 6, ...
    @(x) isnumeric(x) && isscalar(x) && x >= 2);

addParameter(p, 'MinGroups', 4, ...
    @(x) isnumeric(x) && isscalar(x) && x >= 1);

addParameter(p, 'WeakRho', 0.30, ...
    @(x) isnumeric(x) && isscalar(x) && x > 0);

addParameter(p, 'ModerateRho', 0.50, ...
    @(x) isnumeric(x) && isscalar(x) && x > 0);

addParameter(p, 'StrongRho', 0.70, ...
    @(x) isnumeric(x) && isscalar(x) && x > 0);

addParameter(p, 'Alpha', 0.05, ...
    @(x) isnumeric(x) && isscalar(x) && x > 0 && x < 1);

addParameter(p, 'RequireSignificance', false, ...
    @(x) islogical(x) || isnumeric(x));

addParameter(p, 'Verbose', true, ...
    @(x) islogical(x) || isnumeric(x));

parse(p, T_assoc, varargin{:});

label = string(p.Results.Label);

feature_name_var = char(p.Results.FeatureNameVar);
rho_var = char(p.Results.RhoVar);
pearson_var = char(p.Results.PearsonVar);
kendall_var = char(p.Results.KendallVar);
linear_r2_var = char(p.Results.LinearR2Var);
p_var = char(p.Results.PVar);
n_var = char(p.Results.NVar);

min_n = round(p.Results.MinN);
min_groups = round(p.Results.MinGroups);

weak_rho = p.Results.WeakRho;
moderate_rho = p.Results.ModerateRho;
strong_rho = p.Results.StrongRho;

alpha = p.Results.Alpha;
require_significance = logical(p.Results.RequireSignificance);
verbose = logical(p.Results.Verbose);

vars = string(T_assoc.Properties.VariableNames);

required_vars = string({feature_name_var, rho_var, n_var});

for i = 1:numel(required_vars)
    if ~ismember(required_vars(i), vars)
        error('Required variable not found in T_assoc: %s', required_vars(i));
    end
end

has_p = ismember(p_var, vars);
has_pearson = ismember(pearson_var, vars);
has_kendall = ismember(kendall_var, vars);
has_linear_r2 = ismember(linear_r2_var, vars);

T_group = T_assoc;

rho = T_group.(rho_var);
n_valid = T_group.(n_var);

if has_p
    pval = T_group.(p_var);
else
    pval = NaN(height(T_group), 1);
end

T_group.abs_spearman = abs(rho);
T_group.spearman_direction = strings(height(T_group), 1);
T_group.effect_level = strings(height(T_group), 1);
T_group.is_valid_group = false(height(T_group), 1);
T_group.is_significant = false(height(T_group), 1);
T_group.group_decision = strings(height(T_group), 1);

for i = 1:height(T_group)

    if ~isfinite(rho(i)) || n_valid(i) < min_n

        T_group.spearman_direction(i) = "undefined";
        T_group.effect_level(i) = "insufficient";
        T_group.group_decision(i) = "insufficient data";
        continue;

    end

    T_group.is_valid_group(i) = true;

    if rho(i) > 0
        T_group.spearman_direction(i) = "positive";
    elseif rho(i) < 0
        T_group.spearman_direction(i) = "negative";
    else
        T_group.spearman_direction(i) = "zero";
    end

    abs_rho_i = abs(rho(i));

    if abs_rho_i >= strong_rho
        level_i = "strong";
    elseif abs_rho_i >= moderate_rho
        level_i = "moderate";
    elseif abs_rho_i >= weak_rho
        level_i = "weak";
    else
        level_i = "none";
    end

    T_group.effect_level(i) = level_i;

    if has_p
        T_group.is_significant(i) = isfinite(pval(i)) && pval(i) < alpha;
    else
        T_group.is_significant(i) = false;
    end

    if require_significance && has_p && ~T_group.is_significant(i)
        T_group.group_decision(i) = "not supported by p value";
    else
        T_group.group_decision(i) = level_i + " " + T_group.spearman_direction(i);
    end
end

feature_names = unique(string(T_group.(feature_name_var)), 'stable');

T_feature = table();

for fidx = 1:numel(feature_names)

    feature_i = feature_names(fidx);

    mask_feature = string(T_group.(feature_name_var)) == feature_i;
    mask_valid = mask_feature & T_group.is_valid_group;

    rho_i = rho(mask_valid);
    abs_rho_i = abs(rho_i);

    n_total_groups = sum(mask_feature);
    n_valid_groups = sum(mask_valid);

    if n_valid_groups == 0

        row = empty_feature_row(feature_i, n_total_groups, n_valid_groups);
        row.summary_decision = "NO: insufficient valid groups";
        row.recommendation = "Check data availability or grouping size.";

        T_feature = [T_feature; row]; %#ok<AGROW>
        continue;

    end

    p_i = pval(mask_valid);

    if has_pearson
        pearson_i = T_group.(pearson_var)(mask_valid);
    else
        pearson_i = NaN(n_valid_groups, 1);
    end

    if has_kendall
        kendall_i = T_group.(kendall_var)(mask_valid);
    else
        kendall_i = NaN(n_valid_groups, 1);
    end

    if has_linear_r2
        linear_r2_i = T_group.(linear_r2_var)(mask_valid);
    else
        linear_r2_i = NaN(n_valid_groups, 1);
    end

    frac_weak = mean(abs_rho_i >= weak_rho);
    frac_moderate = mean(abs_rho_i >= moderate_rho);
    frac_strong = mean(abs_rho_i >= strong_rho);

    frac_positive = mean(rho_i > 0);
    frac_negative = mean(rho_i < 0);

    direction_consistency = max(frac_positive, frac_negative);

    if frac_positive >= frac_negative
        dominant_direction = "positive";
    else
        dominant_direction = "negative";
    end

    if has_p
        frac_significant = mean(isfinite(p_i) & p_i < alpha);
    else
        frac_significant = NaN;
    end

    median_abs_spearman = median(abs_rho_i, 'omitnan');
    mean_abs_spearman = mean(abs_rho_i, 'omitnan');

    median_spearman = median(rho_i, 'omitnan');
    mean_spearman = mean(rho_i, 'omitnan');

    median_pearson = median(pearson_i, 'omitnan');
    median_kendall = median(kendall_i, 'omitnan');
    median_linear_R2 = median(linear_r2_i, 'omitnan');

    evidence_score = median_abs_spearman * frac_moderate * direction_consistency;

    [summary_decision, recommendation] = make_feature_decision( ...
        n_valid_groups, ...
        min_groups, ...
        median_abs_spearman, ...
        frac_weak, ...
        frac_moderate, ...
        frac_strong, ...
        direction_consistency, ...
        frac_significant, ...
        has_p, ...
        require_significance, ...
        weak_rho, ...
        moderate_rho, ...
        strong_rho);

    row = table();

    row.feature_name = feature_i;
    row.n_total_groups = n_total_groups;
    row.n_valid_groups = n_valid_groups;

    row.median_spearman = median_spearman;
    row.mean_spearman = mean_spearman;
    row.median_abs_spearman = median_abs_spearman;
    row.mean_abs_spearman = mean_abs_spearman;

    row.median_pearson = median_pearson;
    row.median_kendall = median_kendall;
    row.median_linear_R2 = median_linear_R2;

    row.frac_weak_or_better = frac_weak;
    row.frac_moderate_or_better = frac_moderate;
    row.frac_strong = frac_strong;

    row.frac_positive = frac_positive;
    row.frac_negative = frac_negative;
    row.direction_consistency = direction_consistency;
    row.dominant_direction = dominant_direction;

    row.frac_significant = frac_significant;
    row.evidence_score = evidence_score;

    row.summary_decision = summary_decision;
    row.recommendation = recommendation;

    T_feature = [T_feature; row]; %#ok<AGROW>

end

T_feature = sortrows(T_feature, ...
    {'summary_decision', 'evidence_score'}, ...
    {'ascend', 'descend'});

if verbose

    fprintf('\n============================================================\n');
    fprintf('Feature-q evidence summary: %s\n', label);
    fprintf('============================================================\n');

    display_vars = { ...
        'feature_name', ...
        'n_valid_groups', ...
        'median_abs_spearman', ...
        'frac_moderate_or_better', ...
        'frac_strong', ...
        'direction_consistency', ...
        'dominant_direction', ...
        'median_linear_R2', ...
        'summary_decision'};

    display_vars = display_vars(ismember(display_vars, ...
        T_feature.Properties.VariableNames));

    disp(T_feature(:, display_vars));

    fprintf('\nInterpretation rules:\n');
    fprintf('  Spearman rho is used as the main monotonic-association metric.\n');
    fprintf('  Pearson and linear R2 are diagnostic only.\n');
    fprintf('  A strong result means the association is large and directionally consistent across groups.\n');

end

end

% =========================================================================
% Local helper functions
% =========================================================================

function row = empty_feature_row(feature_name, n_total_groups, n_valid_groups)

row = table();

row.feature_name = feature_name;
row.n_total_groups = n_total_groups;
row.n_valid_groups = n_valid_groups;

row.median_spearman = NaN;
row.mean_spearman = NaN;
row.median_abs_spearman = NaN;
row.mean_abs_spearman = NaN;

row.median_pearson = NaN;
row.median_kendall = NaN;
row.median_linear_R2 = NaN;

row.frac_weak_or_better = NaN;
row.frac_moderate_or_better = NaN;
row.frac_strong = NaN;

row.frac_positive = NaN;
row.frac_negative = NaN;
row.direction_consistency = NaN;
row.dominant_direction = "undefined";

row.frac_significant = NaN;
row.evidence_score = NaN;

row.summary_decision = "";
row.recommendation = "";

end

function [decision, recommendation] = make_feature_decision( ...
    n_valid_groups, ...
    min_groups, ...
    median_abs_spearman, ...
    frac_weak, ...
    frac_moderate, ...
    frac_strong, ...
    direction_consistency, ...
    frac_significant, ...
    has_p, ...
    require_significance, ...
    weak_rho, ...
    moderate_rho, ...
    strong_rho)

if n_valid_groups < min_groups

    decision = "NO: insufficient groups";
    recommendation = "Use a coarser grouping or generate more samples.";
    return;

end

if require_significance && has_p

    if ~isfinite(frac_significant) || frac_significant < 0.50

        decision = "NO: weak statistical support";
        recommendation = "Association effect may exist, but p-value support is not consistent.";
        return;

    end
end

if median_abs_spearman >= strong_rho && ...
        frac_strong >= 0.50 && ...
        direction_consistency >= 0.80

    decision = "YES: strong consistent association";
    recommendation = "Use this feature as a candidate predictor for local q.";

elseif median_abs_spearman >= moderate_rho && ...
        frac_moderate >= 0.60 && ...
        direction_consistency >= 0.75

    decision = "YES: moderate consistent association";
    recommendation = "Use this feature as a candidate predictor, likely with covariates.";

elseif median_abs_spearman >= weak_rho && ...
        frac_weak >= 0.50

    decision = "MAYBE: weak or mixed association";
    recommendation = "Keep as candidate, but combine with other features or context variables.";

else

    decision = "NO: no consistent association";
    recommendation = "Do not use this feature alone for q prediction.";

end

end
