function composition = predict_composition( ...
    feature_table, composition_models)
%PREDICT_COMPOSITION Apply frozen patch-composition models.

arguments
    feature_table table
    composition_models struct
end

required_fields = [
    "base_features"
    "purity"
    "mixed"
    "strong_mixed"
];

for field_name = required_fields.'
    if ~isfield(composition_models, field_name)
        error( ...
            "adaptive_req:InvalidCompositionModels", ...
            "Composition model container is missing '%s'.", ...
            field_name);
    end
end

base_features = ...
    string(composition_models.base_features(:));

predictors = ...
    adaptive_req.inference.validate_predictor_table( ...
        feature_table, ...
        base_features, ...
        "composition models");

predicted_purity = ...
    double(predict( ...
        composition_models.purity, ...
        predictors));

[~, mixed_scores] = ...
    predict( ...
        composition_models.mixed, ...
        predictors);

[~, strong_mixed_scores] = ...
    predict( ...
        composition_models.strong_mixed, ...
        predictors);

composition = struct();

composition.predicted_patch_purity = ...
    min(max(predicted_purity(:), 0), 1);

composition.p_mixed = ...
    positive_class_score( ...
        composition_models.mixed, ...
        mixed_scores);

composition.p_strong_mixed = ...
    positive_class_score( ...
        composition_models.strong_mixed, ...
        strong_mixed_scores);

names = fieldnames(composition);

for index = 1:numel(names)
    values = composition.(names{index});

    if any(~isfinite(values))
        error( ...
            "adaptive_req:InvalidCompositionPrediction", ...
            "Composition prediction '%s' contains non-finite values.", ...
            names{index});
    end
end

end


function probability = positive_class_score(model, scores)

class_names = string(model.ClassNames(:));

positive_index = find( ...
    class_names == "true" | ...
    class_names == "1", ...
    1);

if isempty(positive_index)
    if size(scores, 2) == 2
        positive_index = 2;
    else
        error( ...
            "adaptive_req:UnknownPositiveClass", ...
            "Could not identify the positive classifier class.");
    end
end

probability = ...
    double(scores(:, positive_index));

probability = ...
    min(max(probability(:), 0), 1);

end
