function predictor_table = validate_predictor_table( ...
    feature_table, predictor_names, context)
%VALIDATE_PREDICTOR_TABLE Validate and select model predictor columns.

arguments
    feature_table table
    predictor_names
    context {mustBeTextScalar} = "model"
end

predictor_names = string(predictor_names(:));
context = string(context);

if isempty(predictor_names)
    error( ...
        "adaptive_req:EmptyPredictorList", ...
        "%s has no configured predictors.", ...
        context);
end

if numel(unique(predictor_names)) ~= ...
        numel(predictor_names)
    error( ...
        "adaptive_req:DuplicatePredictors", ...
        "%s predictor list contains duplicates.", ...
        context);
end

available_names = ...
    string(feature_table.Properties.VariableNames);

missing_names = ...
    setdiff(predictor_names, available_names, "stable");

if ~isempty(missing_names)
    error( ...
        "adaptive_req:MissingPredictors", ...
        "%s is missing required predictors: %s", ...
        context, ...
        strjoin(missing_names, ", "));
end

for predictor_name = predictor_names.'
    values = ...
        feature_table.(char(predictor_name));

    if ~(isnumeric(values) || islogical(values))
        error( ...
            "adaptive_req:InvalidPredictorType", ...
            "Predictor '%s' for %s is not numeric.", ...
            predictor_name, ...
            context);
    end

    if any(~isfinite(double(values)), "all")
        error( ...
            "adaptive_req:NonfinitePredictors", ...
            "Predictor '%s' for %s contains non-finite values.", ...
            predictor_name, ...
            context);
    end
end

predictor_table = ...
    feature_table(:, cellstr(predictor_names));

end
