function FIGS = plot_run_summary(T_raw, sweep, RUN)
%PLOT_RUN_SUMMARY Generate summary plots for a configured adaptive_req run.

FIGS = struct();

PLOT = RUN.PLOT;
SAVE = RUN.SAVE;

if PLOT.show_q_vs_aperture

    FIGS.q_vs_aperture = adaptive_req.figures.plot_q_vs_aperture( ...
        T_raw, sweep, ...
        'UseOmega', true, ...
        'ShowRaw', true, ...
        'ShowErrorbar', true, ...
        'Title', 'Reference quantile vs aperture');

    save_if_requested(FIGS.q_vs_aperture, PLOT, SAVE, 'q_vs_aperture');
end

if PLOT.show_feature_space

    FIGS.feature_space = adaptive_req.figures.plot_feature_space( ...
        T_raw, ...
        'XFeature', 'ang_entropy', ...
        'YFeature', 'radial_entropy', ...
        'ColorVariable', 'q_theory', ...
        'Title', 'Feature space colored by q_{theory}');

    save_if_requested(FIGS.feature_space, PLOT, SAVE, ...
        'feature_space_q_theory');
end

if PLOT.show_feature_vs_q

    FIGS.ang_entropy_vs_q = adaptive_req.figures.plot_feature_vs_q( ...
        T_raw, ...
        'ang_entropy', ...
        'ColorBy', 'Omega_sr');

    save_if_requested(FIGS.ang_entropy_vs_q, PLOT, SAVE, ...
        'ang_entropy_vs_q');

    FIGS.radial_entropy_vs_q = adaptive_req.figures.plot_feature_vs_q( ...
        T_raw, ...
        'radial_entropy', ...
        'ColorBy', 'Omega_sr');

    save_if_requested(FIGS.radial_entropy_vs_q, PLOT, SAVE, ...
        'radial_entropy_vs_q');
end

if PLOT.show_feature_grid

    [FIGS.features_vs_q_grid, FIGS.fit_table] = ...
        adaptive_req.figures.plot_features_vs_q_grid( ...
            T_raw, ...
            'ColorBy', 'Omega_sr');

    fprintf('\nFeature vs q fit summary.\n');
    disp(FIGS.fit_table);

    save_if_requested(FIGS.features_vs_q_grid, PLOT, SAVE, ...
        'features_vs_q_grid');
end

if PLOT.show_selected_step_wavefield

    if PLOT.store_wavefields

        selected_step = min(RUN.EXP.selected_step, sweep.num_steps);

        FIGS.selected_step_wavefield = ...
            adaptive_req.figures.plot_step_wavefield( ...
                sweep, selected_step, ...
                'Realization', 1, ...
                'ShowPatches', true, ...
                'NumPatches', RUN.EXP.num_patches);

    else

        warning(['Selected-step wavefield plot requested, but ', ...
                 'RUN.PLOT.store_wavefields is false.']);

    end
end

if PLOT.show_all_step_wavefields

    if PLOT.store_wavefields

        FIGS.all_step_wavefields = ...
            adaptive_req.figures.plot_sweep_wavefields( ...
                sweep, ...
                'Realization', 1);

    else

        warning(['All-step wavefield plot requested, but ', ...
                 'RUN.PLOT.store_wavefields is false.']);

    end
end

end

function save_if_requested(fig_handle, PLOT, SAVE, base_name)

if ~PLOT.save_summary_figures
    return;
end

if isempty(fig_handle) || ~isvalid(fig_handle)
    return;
end

adaptive_req.figures.save_figure_bundle( ...
    fig_handle, ...
    SAVE.figure_dir, ...
    base_name, ...
    'SavePNG', SAVE.save_png, ...
    'SavePDF', SAVE.save_pdf, ...
    'SaveFIG', SAVE.save_fig, ...
    'Resolution', SAVE.png_resolution, ...
    'CloseAfterSave', SAVE.close_after_save);

end