function s = combine_feature_structs(radial, angular)

s = struct();

radial_fields = { ...
    'radial_entropy', ...
    'width_75_25_rel', ...
    'width_90_50_rel', ...
    'width_90_10_rel', ...
    'lowk_frac_rel', ...
    'midband_frac_rel', ...
    'highk_frac_rel'};

for i = 1:numel(radial_fields)
    name = radial_fields{i};
    s.(name) = radial.(name);
end

angular_fields = { ...
    'ang_entropy', ...
    'circ_var', ...
    'dom_dir_frac', ...
    'window_max_frac', ...
    'window_cf', ...
    'ang_moment_1', ...
    'ang_moment_2', ...
    'ang_moment_4', ...
    'ang_peak_count_rel', ...
    'ang_top1_window_frac', ...
    'ang_top2_window_frac', ...
    'ang_top3_window_frac', ...
    'ang_top2_to_top1', ...
    'ang_peak_separation_deg'};

for i = 1:numel(angular_fields)
    name = angular_fields{i};
    s.(name) = angular.(name);
end

end
