function tests = test_req_single_precision
%TEST_REQ_SINGLE_PRECISION Verify REQ support for single-precision fields.

tests = functiontests(localfunctions);

end


function setupOnce(~)

repository_root = fileparts(fileparts(fileparts( ...
    mfilename("fullpath"))));

addpath(fullfile(repository_root, "src"));

end


function testPrecomputedRadialAverageAcceptsSingle(testCase)

cfg = struct();

cfg.f0 = 500;
cfg.cs_bg = 2.0;
cfg.dx = 0.5e-3;
cfg.dz = 0.5e-3;

feature_cfg = ...
    adaptive_req.config.default_feature_config( ...
        "M", 2, ...
        "cs_guess", 3.0, ...
        "gamma_win", 1.0, ...
        "pad_factor", 1);

[req_cfg, feature_cfg] = ...
    adaptive_req.config.default_req_config( ...
        cfg, ...
        feature_cfg, ...
        "Nbins", "auto", ...
        "Nbins_auto_oversample", 1, ...
        "Nbins_min", 16, ...
        "smooth_sigma", 1);

window_size = ...
    feature_cfg.win_size;

x_m = ...
    ((1:window_size) - ...
     (window_size + 1)/2) * cfg.dx;

z_m = ...
    ((1:window_size) - ...
     (window_size + 1)/2) * cfg.dz;

[X, ~] = meshgrid( ...
    x_m, ...
    z_m);

wavenumber_rad_m = ...
    2*pi*cfg.f0 / cfg.cs_bg;

patch_single = single( ...
    exp(1i * wavenumber_rad_m * X));

verifyClass(testCase, ...
    patch_single, ...
    "single");

[q_value, req_curve] = ...
    adaptive_req.quantile.compute_quantile_from_patch( ...
        patch_single, ...
        cfg, ...
        req_cfg);

verifyTrue(testCase, ...
    isfinite(q_value));

verifyGreaterThanOrEqual(testCase, ...
    q_value, ...
    0);

verifyLessThanOrEqual(testCase, ...
    q_value, ...
    1);

verifyClass(testCase, ...
    req_curve.Srad, ...
    "double");

verifyTrue(testCase, ...
    all(isfinite(req_curve.Srad)));

verifyTrue(testCase, ...
    all(isfinite(req_curve.Ecum)));

verifyGreaterThan(testCase, ...
    sum(req_curve.Srad), ...
    0);

end
