function feat_cfg = default_feature_config(varargin)
%DEFAULT_FEATURE_CONFIG Default spectral feature configuration.
%
% Usage:
%   feat_cfg = adaptive_req.config.default_feature_config();
%   feat_cfg = adaptive_req.config.default_feature_config('M', 4);

p = inputParser;

addParameter(p, 'M', 3, @(x) isnumeric(x) && isscalar(x) && x > 0);
addParameter(p, 'cs_guess', 3.0, @(x) isnumeric(x) && isscalar(x) && x > 0);

addParameter(p, 'gamma_win', 1.0, @(x) isnumeric(x) && isscalar(x) && x > 0);
addParameter(p, 'pad_factor', 1, @(x) isnumeric(x) && isscalar(x) && x >= 0);
addParameter(p, 'smooth_sigma_2d', 1.0, @(x) isnumeric(x) && isscalar(x) && x >= 0);

addParameter(p, 'Nang', 72, @(x) isnumeric(x) && isscalar(x) && x >= 8);
addParameter(p, 'Nrad_plot', 64, @(x) isnumeric(x) && isscalar(x) && x >= 8);
addParameter(p, 'k_plot_qhi', 0.995, @(x) isnumeric(x) && isscalar(x) && x > 0 && x < 1);

addParameter(p, 'radial_smooth_bins', 5, @(x) isnumeric(x) && isscalar(x) && x >= 1);
addParameter(p, 'angular_smooth_bins', 3, @(x) isnumeric(x) && isscalar(x) && x >= 1);

addParameter(p, 'lowk_rel_alpha', 0.50, @(x) isnumeric(x) && isscalar(x) && x > 0);
addParameter(p, 'highk_rel_alpha', 1.50, @(x) isnumeric(x) && isscalar(x) && x > 0);

addParameter(p, 'midband_rel_iqr', 1.00, @(x) isnumeric(x) && isscalar(x) && x >= 0);
addParameter(p, 'midband_min_abs', 0.0, @(x) isnumeric(x) && isscalar(x) && x >= 0);

addParameter(p, 'angular_band_rel_iqr', 1.00, @(x) isnumeric(x) && isscalar(x) && x >= 0);
addParameter(p, 'angular_band_min_abs', 0.0, @(x) isnumeric(x) && isscalar(x) && x >= 0);

addParameter(p, 'window_deg', 20, @(x) isnumeric(x) && isscalar(x) && x > 0 && x <= 360);
addParameter(p, 'angular_peak_min_rel', 0.35, ...
    @(x) isnumeric(x) && isscalar(x) && x > 0 && x <= 1);
addParameter(p, 'angular_peak_suppression_deg', 30, ...
    @(x) isnumeric(x) && isscalar(x) && x > 0 && x <= 180);
addParameter(p, 'angular_peak_max_count', 8, ...
    @(x) isnumeric(x) && isscalar(x) && x >= 1);

addParameter(p, 'win_size', [], @(x) isempty(x) || (isnumeric(x) && isscalar(x) && x >= 3));

parse(p, varargin{:});

feat_cfg = p.Results;

if ~isempty(feat_cfg.win_size)
    feat_cfg.win_size = round(feat_cfg.win_size);

    if mod(feat_cfg.win_size, 2) == 0
        feat_cfg.win_size = feat_cfg.win_size + 1;
    end
end

feat_cfg.feature_names = { ...
    'radial_entropy', ...
    'width_75_25_rel', ...
    'width_90_50_rel', ...
    'width_90_10_rel', ...
    'lowk_frac_rel', ...
    'midband_frac_rel', ...
    'highk_frac_rel', ...
    'ang_entropy', ...
    'circ_var', ...
    'dom_dir_frac', ...
    'window_max_frac', ...
    'window_cf', ...
    'ang_moment_1', ...
    'ang_moment_2', ...
    'ang_moment_4', ...
    'ang_peak_count_rel', ...
    'ang_top1_window_frac', ...
    'ang_top2_window_frac', ...
    'ang_top3_window_frac', ...
    'ang_top2_to_top1', ...
    'ang_peak_separation_deg', ...
    'ecum_k10_norm_k50', ...
    'ecum_k25_norm_k50', ...
    'ecum_k75_norm_k50', ...
    'ecum_k90_norm_k50', ...
    'ecum_width_50_rel', ...
    'ecum_width_80_rel', ...
    'ecum_lower_tail_rel', ...
    'ecum_upper_tail_rel', ...
    'ecum_asymmetry_10_90', ...
    'ecum_auc_norm', ...
    'ecum_increment_entropy', ...
    'ecum_increment_peak_frac', ...
    'ecum_slope_max', ...
    'ecum_slope_peak_to_mean'};

end
